### ISSUE TITLE
SPDX SBOM with file info throws AttributeError

### ISSUE THREAD

**Issue by mjschlosser8** [anthonyharrison/sbomaudit#4]
Hello, when attempt to analyze the attached SPDX file (v 2.3 spec), I get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/sbomaudit", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sbomaudit/cli.py", line 180, in main
    ntia_compliance = sbom_audit.audit_sbom(sbom_parser)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sbomaudit/audit.py", line 223, in audit_sbom
    spdx_license = self.license_scanner.find_license(license) not in [
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lib4sbom/license.py", line 164, in find_license
    license_expression.replace(" or ", " OR ")
AttributeError: 'NoneType' object has no attribute 'replace'
```

Command I'm using:
`sbomaudit -i  path_to_file --verbose`

This SPDX has file information included, and parsing that section appears to be where the error happens:
![image](https://github.com/user-attachments/assets/9d8caee2-4556-4021-9cc2-8e9b5478e517)

I attempted analysis with the --disable-license-check flag added and got the same error. The same SBOM in CycloneDX format does not throw the error. This does not occur consistently with SPDXs with file info, as this is the first time I have encountered it analyzing this particular configuration.

SBOM: [NJV_withfiles.spdx.json](https://github.com/user-attachments/files/18169288/NJV_withfiles.spdx.json)

**Comment by anthonyharrison** [comment]
@mjschlosser8 Thanks. The issue is with the file information not having an associated licence attribute It requires a very small update to lib4sbom to make it more robust.

Whilst looking at the SBOM, I noted that all of the files have a SHA1 field of 000000000000000000000000. Doesn't seem right!
